server:
  extraScrapeConfigs:
      - job_name: "argocd-server"
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
              - argocd
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: argocd-server
        - source_labels: [__meta_kubernetes_service_port_name]
          action: keep
          regex: metrics
        - source_labels:
              - __meta_kubernetes_service_name
          target_label: service
        - source_labels:
              - __meta_kubernetes_namespace
          target_label: namespace
      - job_name: "argocd-applicationset-controller"
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
              - argocd
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: argocd-applicationset-controller
        - source_labels: [__meta_kubernetes_service_port_name]
          action: keep
          regex: metrics
        - source_labels:
              - __meta_kubernetes_service_name
          target_label: service
        - source_labels:
              - __meta_kubernetes_namespace
          target_label: namespace
      - job_name: "argocd-repo-server"
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
              - argocd
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: argocd-repo-server
        - source_labels: [__meta_kubernetes_service_port_name]
          action: keep
          regex: metrics
        - source_labels:
              - __meta_kubernetes_service_name
          target_label: service
        - source_labels:
              - __meta_kubernetes_namespace
          target_label: namespace
      - job_name: "argocd-server-metrics"
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
              - argocd
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: argocd-metrics
        - source_labels: [__meta_kubernetes_service_port_name]
          action: keep
          regex: metrics
        - source_labels:
              - __meta_kubernetes_service_name
          target_label: service
        - source_labels:
              - __meta_kubernetes_namespace
          target_label: namespace
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
              - cadvisor
        relabel_configs:
        - action: keep
          source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
          regex: "true"
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_path
          target_label: __metrics_path__
          regex: (.+)
        - action: replace
          source_labels:
            - __address__
            - __meta_kubernetes_pod_annotation_prometheus_io_port
          target_label: __address__
          regex: (.+):(?:\d+);(.+)
          replacement: $1:$2
