---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  extension.config: |-
    extensions:
      - name: metrics
        backend:
          services:
            #- url: http://argocd-metrics-server.default.svc.cluster.local:9003
            - url: http://argocd-metrics-server:9003
