# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  config.json: |
    {
    "prometheus": {
      "applications": [
        {
          "name": "default",
          "default": true,
          "dashboards": [
            {
              "groupKind": "pod",
              "tabs": ["Golden Signal"],
              "rows": [
                    {
                  "name": "pod",
                  "title": "Pods",
                  "tab": "Golden Signal",
                  "graphs": [
                    {
                      "name": "pod_cpu_line",
                      "title": "CPU",
                      "description": "",
                      "graphType": "line",
                      "metricName": "pod",
                      "queryExpression": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name=~\"{{.name}}.*\"}[5m])) by (container_label_io_kubernetes_pod_name)"
                    },
                    {
                      "name": "pod_cpu_pie",
                      "title": "CPU Avg",
                      "description": "",
                      "graphType": "pie",
                      "metricName": "pod",
                      "queryExpression": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name=~\"{{.name}}.*\"}[5m])) by (container_label_io_kubernetes_pod_name)"
                    },
                    {
                      "name": "pod_memory_line",
                      "title": "Memory",
                      "description": "",
                      "graphType": "line",
                      "metricName": "pod",
                      "queryExpression": "container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"{{.name}}.*\"}"
                    },
                    {
                      "name": "pod_memory_pie",
                      "title": "Mem Avg",
                      "description": "",
                      "graphType": "pie",
                      "metricName": "pod",
                      "queryExpression": "container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"{{.name}}.*\"}"
                    }
                  ]
                    }
              ]
         }       
         ]
         }
         ],
      "provider":
      {
        "Name": "default",
        "default": true,
        "address": "http://in-cluster-prom-prometheus-server.prom.svc.cluster.local:80"
      }
      }
      }
kind: ConfigMap
metadata:
  name: argocd-metrics-server-configmap
