kind: Secret
apiVersion: v1
metadata:
  name: vault-example
  annotations:
    avp.kubernetes.io/path: "secret/data/webapp/config"
type: Opaque
stringData:
  username: <username>
  password: <password>
